minimumReleaseAgeExclude:
    - '@pnpm/exe@10.34.6'
    - '@pnpm/linux-arm64@10.34.6'
    - '@pnpm/linux-x64@10.34.6'
    - '@pnpm/macos-arm64@10.34.6'
    - '@pnpm/macos-x64@10.34.6'
    - '@pnpm/win-arm64@10.34.6'
    - '@pnpm/win-x64@10.34.6'
